from setuptools import setup

setup(name='lasotuvi',
      version='0.1.2',
      description='Chương trình an sao tử vi mã nguồn mở',
      url='https://github.com/levuphuc/lasotuvi',
      author='levuphuc',
      author_email='levuphuc@gmail.com',
      license='MIT',
      packages=['lasotuvi'],
      python_requires='>=3.9',
      setup_requires=['pytest-runner'],
      tests_require=['pytest'],
      install_requires=[
          "attrs>=23.1.0",
          "ephem>=4.1.4; sys_platform == 'linux'",
          "more-itertools>=10.1.0",
          "mypy>=1.7.0",
          "pluggy>=1.3.0",
          "py>=1.11.0",
          "pytest>=7.4.0",
          "six>=1.16.0",
      ],
      classifiers=[
          'Development Status :: 4 - Beta',
          'Intended Audience :: Developers',
          'License :: OSI Approved :: MIT License',
          'Programming Language :: Python :: 3',
          'Programming Language :: Python :: 3.9',
          'Programming Language :: Python :: 3.10',
          'Programming Language :: Python :: 3.11',
          'Programming Language :: Python :: 3.12',
          'Programming Language :: Python :: 3.13',
      ],
      zip_safe=False)
